import React from "react";
import H2 from "@/components/H2";
import Text from "@/components/Text";
import RarityCard from "@/components/RarityCard";
import styled from "styled-components";
import Image from "next/image";
import { content_width } from "@/constants";
import Marquee from "react-fast-marquee";

const RarityBanner = () => {
  return (
    <StyledRarityBanner>
      <div className="rarity-wrapper">
        <H2>Rarity</H2>
        <Text className="rarity-text">
          Each NFT is algorithmically generated by combining multipe unique
          traits across different categories. There are only 31 legendary and
          135 rare NFTs available for grabs.
        </Text>
      </div>
      <div className="cards-wrapper">
        {[
          {
            title: "Stacks web wallet",
            src: "/icon-1.svg",
          },
          {
            title: "DeFi plateform alex",
            src: "/icon-2.svg",
          },
          {
            title: "Xverse app Jolocam",
            src: "/icon-3.svg",
          },
          {
            title: "Xverse meta wallet",
            src: "/icon-4.svg",
          },
        ].map((item, index) => (
          <RarityCard key={index} src={item.src} title={item.title} />
        ))}
      </div>
      <Marquee className="monster-marquee">
        {[
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
        ].map((item, index) => (
          <div className="image-wrapper">
            <Image
              className="monster-img"
              key={index + 1}
              src={`${item}.png`}
              alt="silly-monster"
              width={388}
              height={387}
            />
          </div>
        ))}
      </Marquee>
      <Marquee className="monster-marquee" direction="right">
        {[
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
        ].map((item, index) => (
          <div className="image-wrapper">
            <Image
              className="monster-img"
              key={index + 1}
              src={`${item}.png`}
              alt="silly-monster"
              width={388}
              height={387}
            />
          </div>
        ))}
      </Marquee>
      <Marquee className="monster-marquee">
        {[
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
          "/monster-1",
        ].map((item, index) => (
          <div className="image-wrapper">
            <Image
              className="monster-img"
              key={index + 1}
              src={`${item}.png`}
              alt="silly-monster"
              width={388}
              height={387}
            />
          </div>
        ))}
      </Marquee>
    </StyledRarityBanner>
  );
};

export default RarityBanner;

const StyledRarityBanner = styled.div`
  background: #000;
  border-radius: 50px;
  padding-bottom: 8rem;
  .rarity-wrapper {
    width: ${content_width};
    display: flex;
    align-items: center;
    padding: 6rem 0;
    margin: 0 auto;
    .rarity-text {
      width: 50%;
      padding-left: 8rem;
    }
  }
  .cards-wrapper {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    width: ${content_width};
    margin: 0 auto;
    margin-bottom: 6rem;
  }
  .monster-marquee {
    // margin-bottom: 1rem;
    .rfm-initial-child-container {
      display: flex;
    }
  }
  .image-wrapper {
    margin: 1rem;
  }
`;
