import React from "react";
import Head from "next/head";
import MainPage from "./MainPage";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Silly Monster</title>
        <meta name="description" content="Generated by Silly Monster" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPage />
      </main>
    </React.Fragment>
  );
}
